name: Build Project with Maven and Test Safari

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-safari:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Build with Maven
        run: mvn clean install

      - name: Run Safari Tests
        run: mvn test -Dbrowser=safari
