name: Test suits

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use macOS container for Safari

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      # Install Safari browser and enable WebDriver
      - name: Enable Safari WebDriver
        run: sudo safaridriver --enable


      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test
